name: clone workflow
on:
  workflow_dispatch:
jobs:
  job_one:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrests.HOST }}
          username: ${{ secrests.USERNAME }}
          password: ${{ secrests.PASSWORD }}
          port: ${{ secrests.PORT }}
          script: |
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            git clone git@github.com:kashifp/cmsc389T-web-template.git
